/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.khachsan.ui;

import com.khachsan.dao.*;
import com.khachsan.entity.*;
import com.khachsan.utils.MsgBox;
import com.khachsan.utils.XDate;
import java.awt.event.KeyEvent;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author nguye
 */
public class DatPhongJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DatPhongJDialog
     */
    public DatPhongJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKhachHangDenQuay = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtMaPhieuDatPhong = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        btnDeleteDatPhong = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNgayDatPhong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNgayTraPhong = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        cboLoaiPhong = new javax.swing.JComboBox<>();
        cboPhong = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChiTietPhieuDatPhong = new javax.swing.JTable();
        btninsertchiTietPhieuDatPhong = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuDatPhong = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        txtHoTenTim = new javax.swing.JTextField();
        txtSoDienThoaiTim = new javax.swing.JTextField();
        btnTimKhachHang = new javax.swing.JButton();
        btnDatPhong = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCanCuocCongDan = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btnFirt = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Mã khách hàng:");

        txtMaKhachHangDenQuay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKhachHangDenQuayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Thông tin khách hàng");

        jLabel16.setText("Mã phiếu đặt phòng");

        txtMaPhieuDatPhong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaPhieuDatPhongKeyPressed(evt);
            }
        });

        btnDeleteDatPhong.setText("Xóa");
        btnDeleteDatPhong.setPreferredSize(new java.awt.Dimension(85, 30));
        btnDeleteDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDatPhongActionPerformed(evt);
            }
        });
        jPanel13.add(btnDeleteDatPhong);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaKhachHangDenQuay)
                    .addComponent(txtMaPhieuDatPhong)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel16)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaPhieuDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaKhachHangDenQuay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
        );

        jLabel8.setText("Ngày đặt phòng:");

        jLabel9.setText("Ngày trả phòng:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayDatPhong)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNgayTraPhong))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgayTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        cboLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiPhongActionPerformed(evt);
            }
        });

        jLabel10.setText("Loại phòng:");

        jLabel11.setText("Phòng:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboPhong, 0, 226, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLoaiPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 153));
        jLabel15.setText("Thông tin phòng");

        tblChiTietPhieuDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phòng", "Ngày đặt phòng", "Ngày trả phòng"
            }
        ));
        jScrollPane2.setViewportView(tblChiTietPhieuDatPhong);

        btninsertchiTietPhieuDatPhong.setText("Thêm");
        btninsertchiTietPhieuDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertchiTietPhieuDatPhongActionPerformed(evt);
            }
        });

        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Sửa");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btninsertchiTietPhieuDatPhong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninsertchiTietPhieuDatPhong)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        tabs.addTab("ĐẶT PHÒNG", jPanel1);

        tblPhieuDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PHIẾU ĐẶT PHÒNG", "KHÁCH HÀNG", "NGÀY LẬP"
            }
        ));
        tblPhieuDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuDatPhongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieuDatPhong);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1142, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addGap(77, 77, 77))
        );

        tabs.addTab("PHIẾU ĐẶT", jPanel2);

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ KHÁCH HÀNG", "HỌ TÊN", "CĂN CƯỚC CÔNG DÂN", "SỐ ĐIỆN THOẠI", "ĐỊA CHỈ", "GIỚI TÍNH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKhachHang);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        txtHoTenTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenTimActionPerformed(evt);
            }
        });
        jPanel9.add(txtHoTenTim);

        txtSoDienThoaiTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiTimActionPerformed(evt);
            }
        });
        jPanel9.add(txtSoDienThoaiTim);

        btnTimKhachHang.setText("Tìm");
        btnTimKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKhachHangActionPerformed(evt);
            }
        });
        jPanel9.add(btnTimKhachHang);

        btnDatPhong.setText("ĐẶT PHÒNG");
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDatPhong)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDatPhong)
                .addContainerGap())
        );

        tabs.addTab("DANH SÁCH", jPanel7);

        jLabel3.setText("MÃ KHÁCH HÀNG");

        jLabel4.setText("SỐ ĐIỆN THOẠI");

        jLabel5.setText("HỌ VÀ TÊN");

        jLabel6.setText("CĂN CƯỚC CÔNG DÂN");

        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNam);
        rdoNam.setText("NAM");
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNu);
        rdoNu.setText("NỮ");
        rdoNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuActionPerformed(evt);
            }
        });

        jLabel7.setText("GIỚI TÍNH");

        jLabel17.setText("ĐỊA CHỈ");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        txtDiaChi.setColumns(20);
        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtDiaChi.setRows(5);
        jScrollPane4.setViewportView(txtDiaChi);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel11.add(btnThem);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel11.add(btnSua);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel11.add(btnXoa);

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        jPanel11.add(btnMoi);

        btnFirt.setText("<");
        btnFirt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirtActionPerformed(evt);
            }
        });
        jPanel12.add(btnFirt);

        btnPre.setText("<<");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });
        jPanel12.add(btnPre);

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel12.add(btnNext);

        btnLast.setText(">");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jPanel12.add(btnLast);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 547, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addComponent(rdoNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoNu))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCanCuocCongDan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCanCuocCongDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        tabs.addTab("KHÁCH HÀNG", jPanel10);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("QUẦY ĐẶT PHÒNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
            .addGroup(layout.createSequentialGroup()
                .addGap(432, 432, 432)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabs))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhieuDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuDatPhongMouseClicked

    }//GEN-LAST:event_tblPhieuDatPhongMouseClicked

    private void txtMaKhachHangDenQuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKhachHangDenQuayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKhachHangDenQuayActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        if(evt.getClickCount()==2){
            this.row = tblKhachHang.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void txtHoTenTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenTimActionPerformed

    private void btnTimKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKhachHangActionPerformed
        // TODO add your handling code here:
        this.fillTable();
    }//GEN-LAST:event_btnTimKhachHangActionPerformed

    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatPhongActionPerformed
        // TODO add your handling code here:
        this.insertdatPhong();
        this.fillTablePhieuDatPhong();
    }//GEN-LAST:event_btnDatPhongActionPerformed

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNamActionPerformed

    private void rdoNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNuActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnFirtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirtActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btnFirtActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void txtSoDienThoaiTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiTimActionPerformed

    private void btnDeleteDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDatPhongActionPerformed
        // TODO add your handling code here:
        this.deletedatphong();
    }//GEN-LAST:event_btnDeleteDatPhongActionPerformed

    private void cboLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiPhongActionPerformed
        // TODO add your handling code here:
        this.fillComboboxPhong();
    }//GEN-LAST:event_cboLoaiPhongActionPerformed

    private void btninsertchiTietPhieuDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertchiTietPhieuDatPhongActionPerformed
        // TODO add your handling code here:
        this.insertChiTietPhieuDatPhong();
        this.fillTableChiTietPhieuDatPhong();
    }//GEN-LAST:event_btninsertchiTietPhieuDatPhongActionPerformed

    private void txtMaPhieuDatPhongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaPhieuDatPhongKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.fillTableChiTietPhieuDatPhong();
        }
    }//GEN-LAST:event_txtMaPhieuDatPhongKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.deleteChiTietPhieuDatPhong();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.updateChiTietPhieuDatPhong();
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatPhongJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DatPhongJDialog dialog = new DatPhongJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnDeleteDatPhong;
    private javax.swing.JButton btnFirt;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKhachHang;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btninsertchiTietPhieuDatPhong;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboLoaiPhong;
    private javax.swing.JComboBox<String> cboPhong;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblChiTietPhieuDatPhong;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTable tblPhieuDatPhong;
    private javax.swing.JTextField txtCanCuocCongDan;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHoTenTim;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaKhachHangDenQuay;
    private javax.swing.JTextField txtMaPhieuDatPhong;
    private javax.swing.JTextField txtNgayDatPhong;
    private javax.swing.JTextField txtNgayTraPhong;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtSoDienThoaiTim;
    // End of variables declaration//GEN-END:variables
void init(){
    this.setLocationRelativeTo(null);
    this.setTitle("KHACH SAN - QUAN LY DAT PHONG");
    this.row = -1;
    this.fillTable();
    this.fillComboBoxLoaiPhong();
    this.fillTablePhieuDatPhong();
}
KhachHangDAO khachHangDao = new KhachHangDAO();
int row = -1;


    void insert(){
        KhachHang kh = getForm();
        try{
            khachHangDao.insert(kh);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this,"Them moi thanh cong!");
        }catch (Exception e){
            MsgBox.alert(this,"Them moi that bai!");
        }
    }
    void update(){
        KhachHang kh = getForm();
        try {
            khachHangDao.update(kh);
            this.fillTable();
            MsgBox.alert(this,"Cap nhat thanh cong");
        }catch (Exception e){
            MsgBox.alert(this,"Cap nhat that bai!");
        }
    }
    void delete(){
        String makh = txtMaKH.getText();
       if(MsgBox.confirm(this,"Ban thuc su muon xoa khach hang nay")){
           try {
               khachHangDao.delete(makh);
               this.clearForm();
               this.fillTable();
               MsgBox.alert(this, "Xoa thanh cong");
           }catch (Exception e){
               MsgBox.alert(this,"Xoa that bai");
           }
       }
    }
    void clearForm(){
        KhachHang kh = new KhachHang();
        kh.setGioiTinh(true);
        setForm(kh);
        this.row = -1;
        this.updateStatus();
    }
    void edit(){
        String makh = (String) tblKhachHang.getValueAt(this.row,0);
        KhachHang kh = khachHangDao.selectById(makh);
        this.setForm(kh);
        tabs.setSelectedIndex(3);
        this.updateStatus();
    }
    void first(){
        this.row = 0;
        this.edit();
    }
    void prev(){
        if(this.row > 0){
            this.row--;
            this.edit();
        }
    }
    void next(){
        if(this.row < tblKhachHang.getRowCount()-1){
            this.row ++;
            this.edit();
        }
    }
    void last(){
        this.row = tblKhachHang.getRowCount()-1;
        this.edit();
    }
    void setForm(KhachHang kh){
        txtMaKH.setText(kh.getMaKH());
        txtHoTen.setText(kh.getHoTen());
        txtCanCuocCongDan.setText(kh.getCanCuocCongDan());
        txtSoDienThoai.setText(kh.getSoDienThoai());
        txtDiaChi.setText(kh.getDiaChi());
        if(kh.getGioiTinh()){
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
    }
    KhachHang getForm(){
        KhachHang kh = new KhachHang();
        kh.setMaKH(txtMaKH.getText());
        kh.setHoTen(txtHoTen.getText());
        kh.setCanCuocCongDan(txtCanCuocCongDan.getText());
        kh.setSoDienThoai(txtSoDienThoai.getText());
        kh.setDiaChi(txtDiaChi.getText());
        kh.setGioiTinh(rdoNam.isSelected());
        return kh;
    }
    void updateStatus(){
        // co hang duoc chon
        boolean edit = (this.row >= 0);
        // hang duoc chon '0'
        boolean first = (this.row ==0);
        // hang duoc chon o cuoi
        boolean last = (this.row == tblKhachHang.getRowCount()-1);

        //trang thai form
        txtMaKH.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        //trang thai dieu huong
        btnFirt.setEnabled(edit&&!first);
        btnPre.setEnabled(edit&&!first);
        btnNext.setEnabled(edit&&!last);
        btnLast.setEnabled(edit&&!last);
    }
    void fillTable(){
        String hoten = "";
        hoten = txtHoTenTim.getText();
        String sodienthoai = "";
        sodienthoai = txtSoDienThoaiTim.getText();
        DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0);
        try {
            List<KhachHang> list = khachHangDao.selectByHoTen_SoDienThoai(hoten, sodienthoai);
            for(KhachHang kh:list){
                Object[] row = {kh.getMaKH(),
                                kh.getHoTen(),
                                kh.getCanCuocCongDan(),
                                kh.getSoDienThoai(), 
                                kh.getDiaChi(),
                                kh.getGioiTinh()?"Nam":"Nu"};
                model.addRow(row);
            }
        }catch (Exception e) {
            MsgBox.alert(this, "Loi truy van du lieu");
        }
    }
    // phieu dat phong
    PhieuDatPhongDAO phieuDatPhongDao = new PhieuDatPhongDAO();
    void insertdatPhong() {
    try {
        int row = tblKhachHang.getSelectedRow();
        if (row == -1) {
            // Không có hàng nào được chọn
            MsgBox.alert(this, "Chua chon khach dat phong");
            return;
        }

        String maKhachHang = (String) tblKhachHang.getValueAt(row, 0);
        PhieuDatPhong entity = new PhieuDatPhong();
        entity.setMaKH(maKhachHang);
        
        phieuDatPhongDao.insert(entity); // Chèn phiếu đặt phòng vào database

        tabs.setSelectedIndex(0); // Chuyển tab về tab đầu tiên

        // Truy vấn phiếu đặt phòng mới được chèn dựa trên MaKH
        PhieuDatPhong entity1 = phieuDatPhongDao.select_maPhieuDatPhong_maKhachHang(maKhachHang);

        if (entity1 != null) {
            // Hiển thị thông tin phiếu đặt phòng và khách hàng
            setFormDatPhong(entity1);
        } else {
            MsgBox.alert(this,"Chua co khach dat phong");
        }
    } catch (Exception e) {
        e.printStackTrace();
        MsgBox.alert(this, "Da xay ra loi: " + e.getMessage());
    }
    
}
    void setFormDatPhong(PhieuDatPhong entity){
        txtMaPhieuDatPhong.setText(entity.getMaPhieuDatPhong());
        txtMaKhachHangDenQuay.setText(entity.getMaKH());
    }
    void clearFormDatPhong(){
        txtMaPhieuDatPhong.setText("");
        txtMaKhachHangDenQuay.setText("");
    }
    void deletedatphong(){
        String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
        if(MsgBox.confirm(this,"Ban thuc su muon xoa phieu dat phong nay")){
            try{
                phieuDatPhongDao.delete(maPhieuDatPhong);
                this.clearFormDatPhong();
                MsgBox.alert(this, "Xoa thanh cong");
            }catch(Exception e){
                MsgBox.alert(this, "Xoa that bai");
            }
            
        }
    }
    // dua du lieu len bang tblPhieuDatPhong
    void fillTablePhieuDatPhong(){
        DefaultTableModel model = (DefaultTableModel) tblPhieuDatPhong.getModel();
        model.setRowCount(0);
        try{
            List<PhieuDatPhong> list = new ArrayList<>();
            list = phieuDatPhongDao.selectAll();
            for(PhieuDatPhong entity:list){
                Object[] row = {entity.getMaPhieuDatPhong(),
                                entity.getMaKH(),
                                XDate.toString(entity.getNgayDatPhong(), "yyyy-MM-dd HH:mm:ss")};
                model.addRow(row);
            }
        }catch(Exception e){
            MsgBox.alert(this, "Loi truy van du lieu....");
        }
    }
    
    
    // loaiPhongDao
    LoaiPhongDAO loaiPhongDAO = new LoaiPhongDAO();
    void fillComboBoxLoaiPhong(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiPhong.getModel();
        model.removeAllElements();
        List<LoaiPhong> list = loaiPhongDAO.selectAll();
        for(LoaiPhong lp:list){
            model.addElement(lp);
        }
        this.fillComboboxPhong();
    }
    // phongDao
    PhongDAO phongDao = new PhongDAO();
    void fillComboboxPhong(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboPhong.getModel();
        String ngayDatPhong = txtNgayDatPhong.getText();
        String ngayTraPhong = txtNgayTraPhong.getText();
        model.removeAllElements();
        
        LoaiPhong loaiPhong = (LoaiPhong) cboLoaiPhong.getSelectedItem();
        if (loaiPhong == null) {
        // Xử lý khi loại phòng không được chọn
        return;
    }
        List<Phong> list = phongDao.get_SELECT_ALL_SQL_Phong_Date_LoaiPhong(ngayDatPhong, ngayDatPhong,loaiPhong.getMaLP());
        for(Phong p:list){
            model.addElement(p);
        }
    }
    // chiTietPhieuDatPhong
    ChiTietPhieuDatPhongDAO chiTietPhieuDatPhongDAO = new ChiTietPhieuDatPhongDAO();
    void insertChiTietPhieuDatPhong(){
        ChiTietPhieuDatPhong entity = getFormChiTietPhieuDatPhong();
        try{
            chiTietPhieuDatPhongDAO.insert(entity);
            this.fillTableChiTietPhieuDatPhong();
            this.clearFormChiTietPhieuDatPhong();
            MsgBox.alert(this,"Them moi thanh cong");
        }catch(Exception e){
            MsgBox.alert(this, "Them moi that bai");
        }
    }
    void updateChiTietPhieuDatPhong() {
    String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
    int row = tblChiTietPhieuDatPhong.getSelectedRow();
    
    // Kiểm tra xem có hàng nào được chọn không
    if (row == -1) {
        MsgBox.alert(this, "Vui lòng chọn một hàng để cập nhật");
        return;
    }

    String maPhong = (String) tblChiTietPhieuDatPhong.getValueAt(row, 0);
    String ngayNhanPhong = (String) tblChiTietPhieuDatPhong.getValueAt(row, 1);
    String ngayTraPhong = (String) tblChiTietPhieuDatPhong.getValueAt(row, 2);

    // In ra giá trị ngày nhận phòng và ngày trả phòng để kiểm tra
    System.out.println("Ngay Nhan Phong: " + ngayNhanPhong);
    System.out.println("Ngay Tra Phong: " + ngayTraPhong);

    ChiTietPhieuDatPhong entity = new ChiTietPhieuDatPhong();
    entity.setMaPhieuDatPhong(maPhieuDatPhong);
    entity.setMaPhong(maPhong);

    try {
        // Phân tích chuỗi ngày giờ thành đối tượng Date
        Timestamp timestamp = new Timestamp(XDate.toDate(ngayNhanPhong, "yyyy-MM-dd HH:mm:ss").getTime());
        entity.setNgayNhanPhong(timestamp);
        Timestamp timestamp3 = new Timestamp(XDate.toDate(ngayTraPhong, "yyyy-MM-dd HH:mm:ss").getTime());
        entity.setNgayTraPhong(timestamp3);

        chiTietPhieuDatPhongDAO.update(entity);
        this.fillTableChiTietPhieuDatPhong();
        MsgBox.alert(this, "Cập nhật thành công");
    } catch (Exception e) {
        MsgBox.alert(this, "Cập nhật thất bại: " + e.getMessage());
    }
}

void fillTableChiTietPhieuDatPhong() {
    String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
    DefaultTableModel model = (DefaultTableModel) tblChiTietPhieuDatPhong.getModel();
    model.setRowCount(0);
    try {
        List<ChiTietPhieuDatPhong> list = chiTietPhieuDatPhongDAO.selectAllmaPhieuDatPhong(maPhieuDatPhong);
        for (ChiTietPhieuDatPhong entity : list) {
            Object[] row = {
                entity.getMaPhong(),
                XDate.toString(entity.getNgayNhanPhong(), "yyyy-MM-dd HH:mm:ss"),
                XDate.toString(entity.getNgayTraPhong(), "yyyy-MM-dd HH:mm:ss")
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        MsgBox.alert(this, "Lỗi truy vấn dữ liệu: " + e.getMessage());
    }
}


    void deleteChiTietPhieuDatPhong(){
        String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
        int row = tblChiTietPhieuDatPhong.getSelectedRow();
        if (row == -1) {
            // Không có hàng nào được chọn
            MsgBox.alert(this, "Chua chon phong");
            return;
        }
        String maPhong = (String) tblChiTietPhieuDatPhong.getValueAt(row, 0);
        if(MsgBox.confirm(this, "Ban thuc su muon xoa phong dat")){
            try{
                chiTietPhieuDatPhongDAO.delete_MaPhieuDatPhong_MaPhong(maPhieuDatPhong, maPhong);
                this.fillTableChiTietPhieuDatPhong();
                MsgBox.alert(this, "Xoa thanh cong");
            }catch(Exception e){
                MsgBox.alert(this, "Xoa that bai");
            }
        }
    }
    void clearFormChiTietPhieuDatPhong(){

    }
    ChiTietPhieuDatPhong getFormChiTietPhieuDatPhong(){
        ChiTietPhieuDatPhong entity = new ChiTietPhieuDatPhong();
        entity.setMaPhieuDatPhong(txtMaPhieuDatPhong.getText());
        Timestamp timestamp = new Timestamp(XDate.toDate(txtNgayDatPhong.getText(), "yyyy-MM-dd HH:mm:ss").getTime());
        entity.setNgayNhanPhong(timestamp);
        Timestamp timestamp3 = new Timestamp(XDate.toDate(txtNgayTraPhong.getText(), "yyyy-MM-dd HH:mm:ss").getTime());
        entity.setNgayTraPhong(timestamp3);
        Phong phong = (Phong) cboPhong.getSelectedItem();
        entity.setMaPhong(phong.getMaPhong());
        return entity;
    }
    
    

}
