/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.khachsan.ui;

import com.khachsan.dao.ChiTietPhieuDatPhongDAO;
import com.khachsan.dao.ChiTietPhieuDichVuDAO;
import com.khachsan.dao.PhieuHoaDonDAO;
import com.khachsan.entity.ChiTietPhieuDatPhong;
import com.khachsan.entity.PhieuHoaDon;
import com.khachsan.utils.Auth;
import com.khachsan.utils.MsgBox;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class HoaDonJDialog extends javax.swing.JDialog {

    /**
     * Creates new form HoaDonJDialog
     */
    public HoaDonJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtMaPhieuDatPhong = new javax.swing.JTextField();
        btnTimMaPhieuDatPhong = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChiTietPhieuDichVu = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblChiTietPhieuDatPhong = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblChiTietPhieuDatPhongDa = new javax.swing.JTable();
        btnLapPhieu1 = new javax.swing.JButton();
        panelToPrint = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblChiTietPhieuDichVuDa = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblChiTietPhieuDatPhongDa1 = new javax.swing.JTable();
        txtSoDienThoaiStore = new javax.swing.JTextField();
        txtPhieuDatPhongStore = new javax.swing.JTextField();
        txtKhachHangStore = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTienPhong = new javax.swing.JTextField();
        txtTienDichVu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPhong = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        txtPhieuHoaDon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("QUẢN LÝ HÓA ĐƠN");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Đặt Phòng\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        txtMaPhieuDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhieuDatPhongActionPerformed(evt);
            }
        });
        jPanel8.add(txtMaPhieuDatPhong);

        btnTimMaPhieuDatPhong.setText("Tìm");
        btnTimMaPhieuDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimMaPhieuDatPhongActionPerformed(evt);
            }
        });
        jPanel8.add(btnTimMaPhieuDatPhong);

        tblChiTietPhieuDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DỊCH VỤ", "ĐƠN GIÁ", "SỐ LẦN SỬ DỤNG", "THÀNH TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblChiTietPhieuDichVu);

        tblChiTietPhieuDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PHÒNG", "NGÀY ĐẶT PHÒNG", "NGÀY TRẢ PHÒNG", "TRẠNG THÁI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiTietPhieuDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietPhieuDatPhongMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblChiTietPhieuDatPhong);

        tblChiTietPhieuDatPhongDa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PHÒNG", "NGÀY ĐẶT PHÒNG", "NGÀY TRẢ PHÒNG", "TRẠNG THÁI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiTietPhieuDatPhongDa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietPhieuDatPhongDaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblChiTietPhieuDatPhongDa);

        btnLapPhieu1.setText("THANH TOÁN");
        btnLapPhieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapPhieu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLapPhieu1)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLapPhieu1)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );

        tabs.addTab("LẬP HÓA ĐƠN", jPanel4);

        jLabel5.setText("PHIẾU ĐẶT PHÒNG");

        jLabel6.setText("KHÁCH HÀNG");

        jLabel10.setText("ĐIỆN THOẠI");

        jLabel21.setText("Cảm ơn Quý Khách!");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("HOA DON");

        jButton1.setText("in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblChiTietPhieuDichVuDa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DỊCH VỤ", "ĐƠN GIÁ", "SỐ LẦN SỬ DỤNG", "THÀNH TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblChiTietPhieuDichVuDa);

        tblChiTietPhieuDatPhongDa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PHÒNG", "ĐƠN GIÁ", "NGÀY ĐẶT PHÒNG", "NGÀY TRẢ PHONG", "THÀNH TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tblChiTietPhieuDatPhongDa1);

        jLabel7.setText("TIỀN PHÒNG");

        jLabel8.setText("TIỀN DỊCH VỤ");

        jLabel9.setText("TỔNG TIỀN");

        jLabel11.setText("PHÒNG");

        jLabel12.setText("NHÂN VIÊN");

        jLabel13.setText("PHIẾU HÓA ĐƠN ");

        javax.swing.GroupLayout panelToPrintLayout = new javax.swing.GroupLayout(panelToPrint);
        panelToPrint.setLayout(panelToPrintLayout);
        panelToPrintLayout.setHorizontalGroup(
            panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToPrintLayout.createSequentialGroup()
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelToPrintLayout.createSequentialGroup()
                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelToPrintLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(72, 72, 72)
                                        .addComponent(txtTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelToPrintLayout.createSequentialGroup()
                                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(26, 26, 26)
                                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhieuDatPhongStore, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhieuHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(39, 39, 39)
                                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTienDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelToPrintLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6))
                                .addGap(41, 41, 41)
                                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKhachHangStore, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoDienThoaiStore, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelToPrintLayout.createSequentialGroup()
                        .addGap(546, 546, 546)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        panelToPrintLayout.setVerticalGroup(
            panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToPrintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jButton1))
                .addGap(24, 24, 24)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhieuHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6)
                    .addComponent(txtKhachHangStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPhieuDatPhongStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoDienThoaiStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelToPrintLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(panelToPrintLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(3, 3, 3)))
                .addGroup(panelToPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGap(9, 9, 9))
        );

        tabs.addTab("XUẤT PHIẾU", panelToPrint);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
            .addGroup(layout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimMaPhieuDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimMaPhieuDatPhongActionPerformed
        // TODO add your handling code here:
        // tblChiTietPhieuDatPhong
        DefaultTableModel model = (DefaultTableModel) tblChiTietPhieuDatPhong.getModel();
        model.setRowCount(0);
        
        // tblChiTietPhieuDatPhongDa
        DefaultTableModel model1 = (DefaultTableModel) tblChiTietPhieuDatPhongDa.getModel();
        model1.setRowCount(0);
        
        //tblChiTietPhieuDichVu
        DefaultTableModel model3 = (DefaultTableModel) tblChiTietPhieuDichVu.getModel();
        model3.setRowCount(0);
        
        //tblChiTietPhieuDatPhongDa1
        DefaultTableModel model5 = (DefaultTableModel) tblChiTietPhieuDatPhongDa1.getModel();
        model5.setRowCount(0);
        
        //tblChiTietPhieuDichVuDa
        DefaultTableModel model7 = (DefaultTableModel) tblChiTietPhieuDichVuDa.getModel();
        model7.setRowCount(0);
        //
        this.fillTableChiTietPhieuDatPhong();
    }//GEN-LAST:event_btnTimMaPhieuDatPhongActionPerformed

    private void txtMaPhieuDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhieuDatPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhieuDatPhongActionPerformed

    private void tblChiTietPhieuDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietPhieuDatPhongMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            this.fillTableChiTietPhieuDichVu();
        }
    }//GEN-LAST:event_tblChiTietPhieuDatPhongMouseClicked

    private void tblChiTietPhieuDatPhongDaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietPhieuDatPhongDaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            this.fillTableChiTietPhieuDatPhongDa1();
            this.fillTableChiTietPhieuDichVuDa();
            tabs.setSelectedIndex(1);
            double tongTien = Double.parseDouble(txtTienDichVu.getText()) + Double.parseDouble(txtTienPhong.getText());
            txtTongTien.setText(String.valueOf(tongTien));
        }
    }//GEN-LAST:event_tblChiTietPhieuDatPhongDaMouseClicked

    private void btnLapPhieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapPhieu1ActionPerformed
        // TODO add your handling code here:
        updatetinhTrang();
        this.insertPhieuhoadon();
        fillTableChiTietPhieuDatPhong();
    }//GEN-LAST:event_btnLapPhieu1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        print();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HoaDonJDialog dialog = new HoaDonJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLapPhieu1;
    private javax.swing.JButton btnTimMaPhieuDatPhong;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel panelToPrint;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblChiTietPhieuDatPhong;
    private javax.swing.JTable tblChiTietPhieuDatPhongDa;
    private javax.swing.JTable tblChiTietPhieuDatPhongDa1;
    private javax.swing.JTable tblChiTietPhieuDichVu;
    private javax.swing.JTable tblChiTietPhieuDichVuDa;
    private javax.swing.JTextField txtKhachHangStore;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMaPhieuDatPhong;
    private javax.swing.JTextField txtPhieuDatPhongStore;
    private javax.swing.JTextField txtPhieuHoaDon;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtSoDienThoaiStore;
    private javax.swing.JTextField txtTienDichVu;
    private javax.swing.JTextField txtTienPhong;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
void init(){
    this.setLocationRelativeTo(null);
    this.setTitle("KHACH SAN - HOA DON");
}
    ChiTietPhieuDatPhongDAO chiTietPhieuDatPhongDao = new ChiTietPhieuDatPhongDAO();
    void fillTableChiTietPhieuDatPhong(){
        String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
        DefaultTableModel model = (DefaultTableModel) tblChiTietPhieuDatPhong.getModel();
        model.setRowCount(0);
        try{
            List<ChiTietPhieuDatPhong> list = chiTietPhieuDatPhongDao.selectAll_MaPhieuDatPhong_Trong(maPhieuDatPhong);
            for(ChiTietPhieuDatPhong entity:list){
                Object[] row = {entity.getMaPhong(),entity.getNgayNhanPhong(),entity.getNgayTraPhong(),entity.getTrangThai()};
                model.addRow(row);
            }
        }catch(Exception e){
            MsgBox.alert(this,"Loi truy van du lieu");
        }
        this.fillTableChiTietPhieuDatPhongDa();
    }
    void fillTableChiTietPhieuDatPhongDa(){
        String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
        DefaultTableModel model = (DefaultTableModel) tblChiTietPhieuDatPhongDa.getModel();
        model.setRowCount(0);
        try{
            List<ChiTietPhieuDatPhong> list = chiTietPhieuDatPhongDao.selectAll_MaPhieuDatPhong_Da(maPhieuDatPhong);
            for(ChiTietPhieuDatPhong entity:list){
                Object[] row = {entity.getMaPhong(),entity.getNgayNhanPhong(),entity.getNgayTraPhong(),entity.getTrangThai()};
                model.addRow(row);
            }
        }catch(Exception e){
            MsgBox.alert(this, "Loi truy van du lieu");
        }
    }
    ChiTietPhieuDichVuDAO chiTietPhieuDichVuDAO = new ChiTietPhieuDichVuDAO();
    void fillTableChiTietPhieuDichVu(){
        int row = tblChiTietPhieuDatPhong.getSelectedRow();

        String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
        String maPhong = (String) tblChiTietPhieuDatPhong.getValueAt(row,0);
        DefaultTableModel model = (DefaultTableModel) tblChiTietPhieuDichVu.getModel();
        model.setRowCount(0);
        try{
            List<Object[]> list = chiTietPhieuDichVuDAO.getChiTietPhieuDichVu(maPhong,maPhieuDatPhong);
            for(Object[] obj:list){
                model.addRow(new Object[]{obj[0],obj[1],obj[2],obj[3]});
            }
        }catch(Exception e){
            MsgBox.alert(this, "Loi truy van du lieu");
        }
    }
    
//
    // Hàm điền dữ liệu vào bảng ChiTietPhieuDatPhongDa1
    void fillTableChiTietPhieuDatPhongDa1(){
        int row = tblChiTietPhieuDatPhongDa.getSelectedRow();
        String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
        String maPhong = (String) tblChiTietPhieuDatPhongDa.getValueAt(row, 0);

        double tienPhong = 0;
        String maPhieuDatPhongStore = "";
        String maKhachHangStore = "";
        String soDienThoaiStore = "";
        String maNhanVien = "";
        String maPhieuHoaDon = "";

        DefaultTableModel model = (DefaultTableModel) tblChiTietPhieuDatPhongDa1.getModel();
        model.setRowCount(0);

        try {
            List<Object[]> list = chiTietPhieuDatPhongDao.getChiTietPhieuDatPhongDa1(maPhong, maPhieuDatPhong);
            for (Object[] obj : list) {
                model.addRow(new Object[]{obj[0], obj[1], obj[2], obj[3], obj[4]});

                // Kiểm tra và xử lý chuỗi rỗng trước khi chuyển đổi
                if (obj[4] != null && !obj[4].toString().isEmpty()) {
                    tienPhong += Double.parseDouble(obj[4].toString());
                }

                maPhieuDatPhongStore = (obj[5] != null) ? obj[5].toString() : "";
                maKhachHangStore = (obj[6] != null) ? obj[6].toString() : "";
                soDienThoaiStore = (obj[7] != null) ? obj[7].toString() : "";
                maNhanVien = (obj[8] != null) ? obj[8].toString() : "";
                maPhieuHoaDon = (obj[9] != null) ? obj[9].toString() : "";
            }
            txtPhong.setText(maPhong);
            txtTienPhong.setText(String.valueOf(tienPhong));
            txtPhieuDatPhongStore.setText(maPhieuDatPhongStore);
            txtKhachHangStore.setText(maKhachHangStore);
            txtSoDienThoaiStore.setText(soDienThoaiStore);
            txtPhieuHoaDon.setText(maPhieuHoaDon);
            txtMaNhanVien.setText(maNhanVien);
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu: " + e.getMessage());
        }
    }

    void fillTableChiTietPhieuDichVuDa(){
        int row = tblChiTietPhieuDatPhongDa.getSelectedRow();
        String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
        String maPhong = (String) tblChiTietPhieuDatPhongDa.getValueAt(row,0);
        // tienDichVu
        double tienDichVu = 0;
        DefaultTableModel model = (DefaultTableModel) tblChiTietPhieuDichVuDa.getModel();
        model.setRowCount(0);
        try{
            List<Object[]> list = chiTietPhieuDichVuDAO.getChiTietPhieuDichVu(maPhong, maPhieuDatPhong);
            for(Object[] obj:list){
                model.addRow(new Object[]{obj[0],obj[1],obj[2],obj[3]});
                tienDichVu += (double) obj[3];
            }
            txtTienDichVu.setText(String.valueOf(tienDichVu));
        }catch(Exception e){
            MsgBox.alert(this,"Loi truy van du lieu");
        }
    }
    // update tinh trang chiTietPhieuDatPhong
    
    void updatetinhTrang(){
        int row = tblChiTietPhieuDatPhong.getSelectedRow();
        String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
        String maPhong = (String) tblChiTietPhieuDatPhong.getValueAt(row,0);
        ChiTietPhieuDatPhong entity = new ChiTietPhieuDatPhong();
        entity.setMaPhieuDatPhong(maPhieuDatPhong);
        entity.setMaPhong(maPhong);
        entity.setTrangThai("Thanh toán");
        try{
        chiTietPhieuDatPhongDao.updatetinhTrang(entity);
        this.fillTableChiTietPhieuDatPhong();
        MsgBox.alert(this,"Cap nhat thanh cong!");
        }catch(Exception e){
            MsgBox.alert(this,"Cap nhat that bai!");
        }
    }
    
    // phieu hoa don
    PhieuHoaDonDAO phieuHoaDonDao = new PhieuHoaDonDAO();
    void insertPhieuhoadon(){
        int row = tblChiTietPhieuDatPhong.getSelectedRow();
        String maPhieuDatPhong = txtMaPhieuDatPhong.getText();
        String maPhong = (String) tblChiTietPhieuDatPhong.getValueAt(row,0);
        String maNhanVien = Auth.user.getMaNV();
        PhieuHoaDon entity = new PhieuHoaDon();
        entity.setMaPhieuDatPhong(maPhieuDatPhong);
        entity.setMaPhong(maPhong);
        entity.setMaNV(maNhanVien);
        try{
            phieuHoaDonDao.insert(entity);
            MsgBox.alert(this, "Them moi thanh cong");
        }catch(Exception e){
            MsgBox.alert(this, "Them moi that bai");
        }
    }
    
    void print() {
        // Tạo một PrinterJob mới
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Panel");

        // Đặt đối tượng Printable và triển khai phương thức print đơn giản hơn
        job.setPrintable((pg, pf, pageNum) -> {
            if (pageNum > 0) {
                return Printable.NO_SUCH_PAGE;
            }

            // In panel với hướng giấy ngang và thu nhỏ kích thước
            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            g2.scale(0.47, 0.47);
            panelToPrint.print(g2);

            return Printable.PAGE_EXISTS;
        });

        // Hiển thị hộp thoại in và thực hiện lệnh in nếu người dùng đồng ý
        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }

    
}
